language: python

python:
  - 3.7

services: postgresql

env:
  - DJANGO=2.2

before_install:
  - export DJANGO_SETTINGS_MODULE=paymentsbackend.settings
  - export PYTHONPATH=$HOME/builds/yourkin/payments-backend
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py syncdb --noinput
