dist: xenial
language: python

python:
  - 3.7

services: postgresql

env:
  - DJANGO=2.2

before_install:
  - export DJANGO_SETTINGS_MODULE=paymentsbackend.settings
  - export PYTHONPATH=$HOME/builds/yourkin/payments-backend
  - export PIP_USE_MIRRORS=true

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate --noinput
